export const fileTypeToCategoryMap = {
  'image/jpeg': 'jpg | image',
  'image/bmp': 'bmp | image',
  'image/gif': 'gif | image',
  'image/png': 'png | image',
  'image/svg+xml': 'svg | image',
  'image/tiff': 'tiff | image',
  'image/webp': 'webp | image',
  'audio/aac': 'aac | audio',
  'audio/midi': 'midi | audio',
  'audio/wav': 'wav | audio',
  'audio/webm': 'webm | audio',
  'audio/x-midi': 'midi | audio',
  'audio/mpeg': 'mp3 | audio',
  'audio/mp4': 'm4a | audio',
  'audio/ogg': 'ogg | audio',
  'audio/3gpp': '3gpp | audio',
  'audio/3gpp2': '3gpp | audio',
  'video/x-msvideo': 'avi | video',
  'video/ogg': 'ogg | video',
  'video/mp4': 'mp4 | video',
  'video/mpeg': 'mpeg | video',
  'video/mp2t': 'ts | video',
  'video/webm': 'webm | video',
  'video/3gpp': '3gpp | video',
  'video/3gpp2': '3gpp | video',
  'application/x-shockwave-flash': 'swf | document',
  'application/pdf': 'pdf | document',
  'application/x-abiword': 'document',
  'application/epub+zip': 'epub | document',
  'application/msword': 'word | document',
  'application/vnd.ms-excel': 'excel | spreadsheet | document',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
    'excel | spreadsheet | document',
  'application/json': 'json | document',
  'application/ogg': 'ogg | document',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
    'word | document',
  'application/x-httpd-php': 'php | document',
  'application/rtf': 'rtf | document',
  'application/vnd.ms-powerpoint': 'presentation | document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation':
    'presentation | document',
  'text/plain': 'txt | document',
  'text/csv': 'csv | document',
  'text/css': 'css | document',
  'application/xml': 'xml | document',
  'text/xml': 'xml | document',
  'application/xhtml+xml': 'xhtml | document',
  'text/html': 'html | document',
  'text/javascript': 'js | document',
  'application/x-javascript': 'js | document',
  'text/x-sh': 'script | document',
  'application/vnd.ms-fontobject': 'font | document',
  'application/otf': 'otf | font | document',
  'application/ttf': 'ttf | font | document',
  'application/woff': 'woff | font | document',
  'application/woff2': 'woff | font | document',
  'application/java-archive': 'jar | compressed',
  'application/x-72-compressed': '7z | compressed',
  'application/zip': 'zip | compressed',
  'application/x-bzip': 'bzip | compressed',
  'application/x-bzip2': 'bzip | compressed',
  'application/gzip': 'gzip | compressed',
  'application/vnd.rar': 'rar | compressed',
};
